name:                edi-parser-scaffolder
version:             20190607
github:              fretlink/edi-parser
author:              FretLink
maintainer:          example@example.com
copyright:           2019 FretLink

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/edi-parser-scaffolder#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  dependencies:
  - bytestring
  - directory
  - filepath
  - formatting
  - mtl
  - pandoc
  - pandoc-types
  - parsec
  - process
  - split
  - text
  - transformers
  - zip-archive

executables:
  edi-parser-scaffolder:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - edi-parser-scaffolder
    - optparse-applicative
