name: edi-parser-core
version: 20190607
synopsis: Example parser for EDI files
description: Please see README.md
category: Text
author: FretLink
maintainer: example@example.com
copyright: 2019 FretLink
github: fretlink/edi-parser

extra-source-files:
- README.md

dependencies:
- text

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  dependencies:
  - base >=4.7 && <5
  - data-default
  - formatting
  - mtl
  - parsec
  - scientific
  - time

tests:
  edi-parser-core-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - base
    - edi-parser-core
    - parsec
    - HUnit
    - test-framework
    - test-framework-hunit
