name: Test PR
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created, edited, published]

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v2
      with:
        version: '2.2.1'
    - name: 'Run HLint'
      uses: haskell/actions/hlint-run@v2
      with:
        path: '["core/", "specification/", "scaffolder/"]'
        fail-on: warning
  build-haskell:
    name: EDI Parser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', '*/package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
      - run: make test
